# Generated by Django 2.2.7 on 2019-12-17 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='universidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Universidad'),
        ),
    ]
