# Generated by Django 3.0 on 2020-01-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191217_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='ciudad',
            field=models.CharField(default='Valledupar', max_length=100, verbose_name='Ciudad'),
        ),
    ]
