# Generated by Django 3.0 on 2020-01-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_inmueble_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='barrio',
            field=models.CharField(max_length=150, verbose_name='Barrio'),
        ),
    ]
