# Generated by Django 3.1 on 2020-08-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200128_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='fechaEntrada',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='fechaSalida',
            field=models.DateField(null=True),
        ),
    ]
