# Generated by Django 3.1.1 on 2020-09-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200807_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
